In [1]:
import sys
print(sys.version)

3.9.12 (main, Jun  1 2022, 11:38:51) 
[GCC 7.5.0]


In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from PIL import Image

# Make NumPy printouts easier to read.
np.set_printoptions(precision=3, suppress=True)

In [4]:
twarz = Image.open('Baza_zdjec/s4/1.pgm')

In [5]:
szer, wyso = twarz.size

In [6]:
print(twarz.size)
plt.imshow(twarz, cmap = 'gray')

(92, 112)


In [11]:
arr_twarz = np.array(twarz)

In [12]:
print(arr_twarz)

[[48 49 45 ... 56 56 54]
 [45 52 39 ... 52 50 51]
 [45 50 42 ... 48 53 50]
 ...
 [50 48 50 ... 45 46 46]
 [45 54 49 ... 46 47 47]
 [51 51 51 ... 47 46 46]]


In [17]:
w, h = 92, 92
data = np.zeros((h, w), dtype=np.uint8)
data[0:w, 0:w] = [255] 

In [19]:
for x in range(w):
    data[x] = arr_twarz[10+x]

In [20]:
con = Image.fromarray(data)

In [21]:
plt.imshow(con, cmap = 'gray')

In [22]:
con_2 = con.resize((int(64), int(64)))
plt.imshow(con_2, cmap = 'gray')